# Generated by Django 5.0.2 on 2024-02-25 14:54

import django.db.models.deletion
import note.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Teal', 'Teal'), ('Pink', 'Pink'), ('Cyan', 'Cyan'), ('Amber', 'Amber'), ('Indigo', 'Indigo'), ('Lime', 'Lime'), ('Brown', 'Brown'), ('Deep Purple', 'Deep Purple'), ('Light Blue', 'Light Blue'), ('Light Green', 'Light Green'), ('Deep Orange', 'Deep Orange'), ('Grey', 'Grey'), ('Blue Grey', 'Blue Grey'), ('White', 'White'), ('Deep Orange Accent', 'Deep Orange Accent'), ('Deep Purple Accent', 'Deep Purple Accent'), ('Green Accent', 'Green Accent'), ('Amber Accent', 'Amber Accent'), ('Blue Accent', 'Blue Accent'), ('Cyan Accent', 'Cyan Accent'), ('Orange Accent', 'Orange Accent'), ('Indigo Accent', 'Indigo Accent'), ('Pink Accent', 'Pink Accent'), ('Red Accent', 'Red Accent')], default=note.models.random_color, max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
