# Generated by Django 5.0.2 on 2024-02-22 03:27

import note.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Teal', 'Teal'), ('Pink', 'Pink'), ('Cyan', 'Cyan'), ('Amber', 'Amber'), ('Indigo', 'Indigo'), ('Lime', 'Lime'), ('Brown', 'Brown'), ('Deep Purple', 'Deep Purple'), ('Light Blue', 'Light Blue'), ('Light Green', 'Light Green'), ('Deep Orange', 'Deep Orange'), ('Grey', 'Grey'), ('Blue Grey', 'Blue Grey'), ('White', 'White'), ('Deep Orange Accent', 'Deep Orange Accent'), ('Deep Purple Accent', 'Deep Purple Accent'), ('Green Accent', 'Green Accent'), ('Amber Accent', 'Amber Accent'), ('Blue Accent', 'Blue Accent'), ('Cyan Accent', 'Cyan Accent'), ('Orange Accent', 'Orange Accent'), ('Indigo Accent', 'Indigo Accent'), ('Pink Accent', 'Pink Accent'), ('Red Accent', 'Red Accent')], default=note.models.random_color, max_length=100),
        ),
    ]
